package com.reicode.ToDoListApplication.model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@NoArgsConstructor
@AllArgsConstructor
@DynamoDBTable(tableName = "todotable")
public class TodoItem {

    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey // allows DynamoDB to automatically generate a unique ID for each item when it is inserted into the table.
    private String id;

    @DynamoDBAttribute(attributeName = "description")
    private String description;

    @DynamoDBAttribute(attributeName = "completed")
    private boolean completed;
}
